-- grid_module.lua
-- Grid firmware entry point for the compiled-song player (lite stack).
--
-- This is the MINIMAL on-device player: a precompiled song table walked
-- by a tiny pulse-clock player.  No sequencer engine on device.
--
-- ── Files to upload to the Grid module ────────────────────────────────────
-- Each library lives in its own folder so it can be uploaded / removed
-- independently.  Generated by:
--   lua tools/gridsplit.lua  --require-prefix /player       \
--                            --outdir grid/player           \
--                            player_lite/player.lua
--   lua tools/song_compile.lua --require-prefix /dark_groove \
--                              --outdir grid/dark_groove     \
--                              songs/dark_groove.lua
--
-- Then upload:
--   grid/player/*.lua       → /player/  on the Grid module
--   grid/dark_groove/*.lua  → /dark_groove/  on the Grid module
--
-- ── Firmware API assumed ──────────────────────────────────────────────────
--   midi_send(channel, status_byte, note, velocity)
--   element_timer_start(element_index, delay_ms)
--   self:element_index()
--
-- ── Clock source ──────────────────────────────────────────────────────────
-- Grid firmware does not expose uv.now().  We maintain SEQ_CLOCK_MS,
-- a simple integer that increments by the timer interval on every tick.
--
-- ── Require paths ─────────────────────────────────────────────────────────
-- Grid's require() resolves the module name as a literal file path; the
-- standard package.path "?" substitution does NOT work.  Therefore every
-- require uses the full path including the leading slash, e.g.
-- require("/player/seq_player").  The splitter and song compiler bake
-- these paths in via --require-prefix so chunks self-load correctly.

-- ═══════════════════════════════════════════════════════════════════════════
-- INIT BLOCK  (paste into element 0 init event — runs once on config load)
-- ═══════════════════════════════════════════════════════════════════════════

local Player = require("/player/seq_player")
local song   = require("/dark_groove/dark_groove")

-- Software ms counter — incremented each tick by SEQ_INTERVAL.
SEQ_CLOCK_MS = 0
local function gridClockFn() return SEQ_CLOCK_MS end

SEQ_PLAYER   = Player.new(song, gridClockFn)
-- Tick interval: the player walks the song against pulses, so we choose a
-- timer rate fine enough to resolve the smallest gate.  Half the pulse
-- interval is plenty.  At BPM 118, ppb 4 → pulse ≈ 127ms → tick ≈ 60ms.
SEQ_INTERVAL = math.floor(SEQ_PLAYER.pulseMs / 2)

-- MIDI emit: route player events to firmware MIDI API.
-- Lite player passes (eventType, pitch, velocity, channel) directly.
function SEQ_EMIT(eventType, pitch, velocity, channel)
    if eventType == "NOTE_ON" then
        midi_send(channel, 0x90, pitch, velocity)
    else
        midi_send(channel, 0x80, pitch, 0)
    end
end

Player.start(SEQ_PLAYER)
element_timer_start(0, SEQ_INTERVAL)

-- ═══════════════════════════════════════════════════════════════════════════
-- TIMER BLOCK  (paste into element 0 timer event — self-restarting loop)
-- ═══════════════════════════════════════════════════════════════════════════

local Player = require("/player/seq_player")

SEQ_CLOCK_MS = SEQ_CLOCK_MS + SEQ_INTERVAL
Player.tick(SEQ_PLAYER, SEQ_EMIT)
element_timer_start(self:element_index(), SEQ_INTERVAL)

-- ═══════════════════════════════════════════════════════════════════════════
-- BUTTON CONTROLS (examples — paste into any button element's press event)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Stop and silence all notes:
--   local Player = require("/player/seq_player")
--   Player.stop(SEQ_PLAYER)
--   local offs = Player.allNotesOff(SEQ_PLAYER)
--   for _, e in ipairs(offs) do
--       midi_send(e.channel, 0x80, e.pitch, 0)
--   end
--
-- Restart from beginning:
--   local Player = require("/player/seq_player")
--   Player.start(SEQ_PLAYER)
--
-- Change BPM live (e.g. from a knob):
--   local Player = require("/player/seq_player")
--   Player.setBpm(SEQ_PLAYER, 140)

-- ═══════════════════════════════════════════════════════════════════════════
-- MIDI CLOCK SYNC  (alternative to the internal-clock TIMER block above)
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Drives the player from incoming MIDI clock (status byte 0xF8) instead of
-- the firmware timer.  Use this when Ableton (or any MIDI clock master) is
-- the tempo source.
--
-- Standard MIDI clock = 24 pulses per quarter note.  The compiled song
-- uses song.pulsesPerBeat (typically 4) per quarter note.  Ratio:
--   midiClocksPerPlayerPulse = 24 / song.pulsesPerBeat
-- For ppb=4 → 6 MIDI clocks per player pulse.
--
-- IMPORTANT: when running in MIDI-sync mode, do NOT also start the timer
-- (skip element_timer_start in INIT).  Otherwise the player will be driven
-- by both clocks and double-advance.
--
-- ── Replacement INIT BLOCK (MIDI-sync mode) ───────────────────────────────
-- (replaces the INIT BLOCK above; do not include element_timer_start)
--
--   local Player = require("/player/seq_player")
--   local song   = require("/dark_groove/dark_groove")
--
--   SEQ_PLAYER       = Player.new(song)            -- no clockFn needed
--   SEQ_MIDI_PER_PULSE = math.floor(24 / song.pulsesPerBeat)
--   SEQ_MIDI_COUNT   = 0
--
--   function SEQ_EMIT(eventType, pitch, velocity, channel)
--       if eventType == "NOTE_ON" then
--           midi_send(channel, 0x90, pitch, velocity)
--       else
--           midi_send(channel, 0x80, pitch, 0)
--       end
--   end
--
--   -- Wait for 0xFA (Start) from the master before running.
--
-- ── rtmidi callback (paste into the element's rtmidi-receive event) ───────
--
--   self.rtmrx_cb = function(self, t)
--       local Player = require("/player/seq_player")
--
--       if t == 0xF8 then                          -- timing clock
--           if SEQ_PLAYER.running then
--               SEQ_MIDI_COUNT = SEQ_MIDI_COUNT + 1
--               if SEQ_MIDI_COUNT >= SEQ_MIDI_PER_PULSE then
--                   SEQ_MIDI_COUNT = 0
--                   Player.externalPulse(SEQ_PLAYER, SEQ_EMIT)
--               end
--           end
--
--       elseif t == 0xFA then                      -- start (rewind to 0)
--           SEQ_MIDI_COUNT = 0
--           Player.start(SEQ_PLAYER)
--
--       elseif t == 0xFB then                      -- continue (resume)
--           SEQ_MIDI_COUNT = 0
--           SEQ_PLAYER.running = true
--
--       elseif t == 0xFC then                      -- stop
--           Player.stop(SEQ_PLAYER)
--           local offs = Player.allNotesOff(SEQ_PLAYER)
--           for _, e in ipairs(offs) do
--               midi_send(e.channel, 0x80, e.pitch, 0)
--           end
--       end
--   end
