#!/usr/bin/env python3
"""build_menu_screen.py -- assemble the grid-wasm preview screen for the seq3
menu/settings GUI from the modular sources.

Inputs (read):
  layout-system/layout_core.lua        -- the Layout engine (verbatim, stripped)
  sequencer-3/ui/menu_widgets.lua      -- the menu widget set (verbatim, stripped)
  sequencer-3/ui/seq3_menu_host.lua    -- host model + tree + control map

Output (written):
  sequencer-3/ui/seq3_menu.lua         -- flat grid-wasm screen script
                                        -- (INIT START/END + LOOP START/END)

The harness has no `require`, so the module bodies are inlined verbatim
(comment-stripped) into function wrappers; a tiny local `require` shim resolves
menu_widgets' `require("layout_core")`. On device the real modules load from
the filesystem and this file is never shipped. The init block builds everything
once (guarded on the `canvas` global, which persists across harness events);
the loop block maps injected control events onto the host control map and
renders. See grid-wasm/INPUT_SPEC.md for the event model.

Usage:  python3 sequencer-3/tools/build_menu_screen.py   (from the repo root)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

SOURCES = [
    ROOT / "layout-system" / "layout_core.lua",
    ROOT / "sequencer-3" / "ui" / "menu_widgets.lua",
    ROOT / "sequencer-3" / "ui" / "seq3_menu_host.lua",
]
OUT = ROOT / "sequencer-3" / "ui" / "seq3_menu.lua"

INIT_BUDGET = 15400  # harness VM init buffer is 16 KB; the injected control
                     # globals block adds ~900 bytes at load time


def strip_comments(src: str) -> str:
    """Drop full-line comments, trailing comments (outside strings) and
    collapse runs of blank lines."""
    out_lines = []
    for line in src.split("\n"):
        in_str = False
        cut = None
        i = 0
        while i < len(line) - 1:
            ch = line[i]
            if ch == '"' or ch == "'":
                in_str = not in_str
            elif not in_str and line.startswith("--", i):
                cut = i
                break
            i += 1
        if cut is not None:
            line = line[:cut]
        line = line.rstrip()
        if not line:
            continue
        out_lines.append(line.lstrip())  # indentation is dead weight at this size
    # collapse runs of blank-ish lines (we removed blanks entirely above, so
    # just rejoin; indentation is preserved on code lines)
    return "\n".join(out_lines)


def read_stripped(path: Path) -> str:
    return strip_comments(path.read_text())


def main() -> int:
    core_src = read_stripped(SOURCES[0])
    widgets_src = read_stripped(SOURCES[1])
    host_src = read_stripped(SOURCES[2])

    init_body = f"""FRAME = FRAME or 0
RC = (RC or 0) + 1   -- init re-runs once per harness event; use it as an
                     -- event sequence number (press-release-press repeats the
                     -- same index/value, so index+value alone is not enough)
pcall(collectgarbage, 'collect')   -- reclaim the previous event's compiled
                                   -- chunk; harness-only, never on device
print('seq3 menu init')
if not canvas then
core = (function()
{core_src}
end)()

MW = (function()
local require = function(name)
  if name == "layout_core" then return core end
  error("seq3 menu preview: module not inlined: " .. tostring(name))
end
{widgets_src}
end)()

{host_src}
end"""

    loop_body = """FRAME = (FRAME or 0) + 1
local sig = tostring(RC or 0)
if sig ~= EVSIG then
  EVSIG = sig
  local i = grid.event_index
  if i == 8 then
    if grid.encoder_delta ~= 0 and handleControl then handleControl(8, grid.encoder_delta) end
  elseif i >= 0 and grid.button_state[i] == 1 and handleControl then
    handleControl(i)
  end
end
if canvas then canvas:render(FRAME) end"""

    init_len = len(init_body)
    if init_len > INIT_BUDGET:
        print(f"ERROR: init block {init_len} bytes exceeds budget {INIT_BUDGET}",
              file=sys.stderr)
        return 1

    out = f"""-- seq3_menu.lua (AUTO-GENERATED by sequencer-3/tools/build_menu_screen.py --
-- do not edit; edit the sources instead)
-- sequencer-3 menu/settings GUI preview for the grid-wasm harness.
--
-- Sources: layout-system/layout_core.lua, sequencer-3/ui/menu_widgets.lua,
-- sequencer-3/ui/seq3_menu_host.lua. The init block builds the Layout, the
-- menu widget and the host once (guarded); the loop block maps the harness's
-- injected control events (grid.event_*) onto the host control map and
-- renders. On device this file is never shipped: the modular sources load
-- from the filesystem and element events dispatch directly.
--
-- Preview (from grid-wasm/, with `python3 -m http.server 8080` in the root):
--   node screenshot.mjs ../sequencer-3/ui/seq3_menu.lua 128 shot.png
-- Interactive: open http://localhost:8080/grid-wasm/index.html and pick
-- seq3_menu in the Screen file dropdown.
--
-- Controls: KS0/1 move cursor, KS2 open, KS3 back, ENC 8 edit value
-- (BTN9-12 mirror open/back/up/down).

-- INIT START
{init_body}
-- INIT END

-- LOOP START
{loop_body}
-- LOOP END
"""

    OUT.write_text(out)
    print(f"wrote {OUT.relative_to(ROOT)}  (init {init_len}b, loop {len(loop_body)}b)")
    return 0


if __name__ == "__main__":
    sys.exit(main())