-- seq2_live.lua (AUTO-GENERATED by tools/build.lua — do not edit)
-- THIN preview: generator ran at BUILD time; these are baked note arrays.
-- No engine embedded. Encoder scrubs; KEY0-3 pick a variant.

-- INIT START
BG={12,12,16} DIM={60,60,60} GREY={130,130,130} WHITE={235,235,235}
ORANGE={249,150,0} DIMOR={150,95,20} CYAN={0,200,220}
PLO=45 PHI=80 LOOP=96
VP={} VS={} VL={} VN={}
VP[0]={50,69,52,71,53,50} VS[0]={0,18,36,48,66,84} VL[0]={8,6,5,5,8,5} VN[0]=6
VP[1]={71,60,60,62,62,52} VS[1]={0,18,36,48,66,84} VL[1]={3,6,3,6,6,7} VN[1]=6
VP[2]={71,52,67,53,69,53} VS[2]={0,18,36,48,66,84} VL[2]={5,7,7,8,3,9} VN[2]=6
VP[3]={69,64,53,67,55,55} VS[3]={0,18,36,48,66,84} VL[3]={6,7,4,3,7,4} VN[3]=6
-- INIT END

-- LOOP START
local sel=0
if uiControlDown then for k=0,3 do if uiControlDown[k]==1 then sel=k end end end
local P,S,L,N=VP[sel],VS[sel],VL[sel],VN[sel]
local ph=math.floor((sliderValue or 0)/255*LOOP)
local rowH=116/(PHI-PLO)
ggdrf(0,0,0,320,240,BG)
local on=0
for i=1,N do
  local s,l,p=S[i],L[i],P[i]
  local x1=2+s/LOOP*316 local x2=2+(s+l)/LOOP*316 if x2-x1<2 then x2=x1+2 end
  local y=118-(p-PLO)*rowH
  local act=(ph>=s and ph<s+l)
  if act then on=on+1 end
  ggdrf(0,x1,y-rowH/2,x2,y+rowH/2,act and ORANGE or DIMOR)
end
local px=2+ph/LOOP*316
ggdl(0,px,0,px,119,CYAN)
ggdl(0,0,120,320,120,DIM)
ggdft(0,'SEQ2 GEN (euclid, A minor)',8,128,8,ORANGE)
ggdft(0,'ENCODER=SCRUB  KEY0-3=VARIANT',8,148,8,GREY)
ggdft(0,'VARIANT',8,168,8,GREY) ggdft(0,tostring(sel),130,168,8,ORANGE)
ggdft(0,'NOTES',170,168,8,GREY) ggdft(0,tostring(N),250,168,8,ORANGE)
ggdft(0,'TICK',8,188,8,GREY) ggdft(0,ph..' / '..LOOP,130,188,8,ORANGE)
ggdft(0,'ON',170,188,8,GREY) ggdft(0,tostring(on),250,188,8,WHITE)
ggdsw()
-- LOOP END
