-- seq3_menu.lua (AUTO-GENERATED by sequencer-3/tools/build_menu_screen.py --
-- do not edit; edit the sources instead)
-- sequencer-3 menu/settings GUI preview for the grid-wasm harness.
--
-- Sources: layout-system/layout_core.lua, sequencer-3/ui/menu_widgets.lua,
-- sequencer-3/ui/seq3_menu_host.lua. The init block builds the Layout, the
-- menu widget and the host once (guarded); the loop block maps the harness's
-- injected control events (grid.event_*) onto the host control map and
-- renders. On device this file is never shipped: the modular sources load
-- from the filesystem and element events dispatch directly.
--
-- Preview (from grid-wasm/, with `python3 -m http.server 8080` in the root):
--   node screenshot.mjs ../sequencer-3/ui/seq3_menu.lua 128 shot.png
-- Interactive: open http://localhost:8080/grid-wasm/index.html and pick
-- seq3_menu in the Screen file dropdown.
--
-- Controls: KS0/1 move cursor, KS2 open, KS3 back, ENC 8 edit value
-- (BTN9-12 mirror open/back/up/down).

-- INIT START
FRAME = FRAME or 0
RC = (RC or 0) + 1   -- init re-runs once per harness event; use it as an
                     -- event sequence number (press-release-press repeats the
                     -- same index/value, so index+value alone is not enough)
pcall(collectgarbage, 'collect')   -- reclaim the previous event's compiled
                                   -- chunk; harness-only, never on device
print('seq3 menu init')
if not canvas then
core = (function()
local M = {}
local function textWidth(text, size) return #text * size end
M.textWidth = textWidth
local function fitSize(text, maxW, maxSize, minSize)
maxSize = maxSize or 32
minSize = minSize or 8
local n = #text
if n == 0 then return minSize end
local s = (maxW // n) // 8 * 8
if s > maxSize then s = maxSize end
if s < minSize then s = minSize end
return s
end
M.fitSize = fitSize
local function centerX(text, size, x, w)
return x + ((w - #text * size) // 2)
end
M.centerX = centerX
local function drawIndicator(lcd, x, y, w, h, style)
local c = style.color or { 0, 120, 255 }
local t = style.thick or 2
local kind = style.kind or "bar-top"
if kind == "bar-top" then
lcd:draw_area_filled(x, y, x + w, y + t, c)
elseif kind == "bar-left" then
lcd:draw_area_filled(x, y, x + t, y + h, c)
elseif kind == "ring" then
lcd:draw_rectangle(x, y, x + w, y + h, c)
elseif kind == "dot-tr" then
local r = style.size or 4
lcd:draw_area_filled(x + w - r, y, x + w, y + r, c)
end
end
M.drawIndicator = drawIndicator
local Layout = {}
Layout.__index = Layout
M.Layout = Layout
function Layout:new()
local o = setmetatable({}, self)
o.children = {}
o.update = { mode = "always" }
o.change = true
return o
end
function Layout:initialize(lcd, cols, rows, x, y, w, h)
self.lcd      = lcd
self.cols     = cols
self.rows     = rows
self.x        = x or 0
self.y        = y or 0
self.w        = w or 320
self.h        = h or 240
self.cellW    = cols and (self.w / cols) or self.w
self.cellH    = rows and (self.h / rows) or self.h
self.children = {}
return self
end
local function attach(self, widget, x, y, w, h)
widget.x, widget.y, widget.w, widget.h = x, y, w, h
widget.lcd    = self.lcd
widget.parent = self
widget.change = true
if widget.cols and widget.initialize == Layout.initialize then
widget.cellW, widget.cellH = w / widget.cols, h / widget.rows
end
self.children[#self.children + 1] = widget
return widget
end
function Layout:addWidget(cx, cy, widget)
return attach(self, widget,
self.x + math.floor(cx * self.cellW),
self.y + math.floor(cy * self.cellH),
math.floor(self.cellW), math.floor(self.cellH))
end
function Layout:place(x, y, w, h, widget)
return attach(self, widget, self.x + x, self.y + y, w, h)
end
local function should_render(cell, frame)
local u = cell.update
if not u or u.mode == "dirty" then
return cell.change == true
elseif u.mode == "always" then
return true
elseif u.mode == "frames" then
return cell.change == true or (frame % (u.n or 1)) == 0
end
return cell.change == true
end
function Layout:render(frame)
frame = frame or 0
local drew = false
for i = 1, #self.children do
local cell = self.children[i]
if cell.children then
if cell:render(frame) then drew = true end
elseif should_render(cell, frame) then
cell:render()
cell.change = false
drew = true
end
end
if self.parent == nil and drew then
self.lcd:draw_swap()
end
return drew
end
function Layout:dispatch(cbName, ...)
for i = 1, #self.children do
local cell = self.children[i]
if cell.children then
cell:dispatch(cbName, ...)
elseif type(cell[cbName]) == "function" then
cell[cbName](cell, ...)
end
end
end
function Layout:hitTest(px, py)
for i = 1, #self.children do
local cell = self.children[i]
if px >= cell.x and px < cell.x + cell.w
and py >= cell.y and py < cell.y + cell.h then
if cell.children then return cell:hitTest(px, py) or cell end
return cell
end
end
return nil
end
return M
end)()

MW = (function()
local require = function(name)
  if name == "layout_core" then return core end
  error("seq3 menu preview: module not inlined: " .. tostring(name))
end
local core = require("layout_core")
local M = {}
function M.menu(opts)
opts = opts or {}
local rows = opts.rows or 6
return {
root = opts.root,
rows = rows,
pad  = opts.pad or 8,
bg      = opts.bg or { 0, 0, 0 },
rule    = opts.rule or { 46, 46, 54 },
title_c = opts.title_c or { 249, 150, 0 },
label_c = opts.label_c or { 130, 130, 130 },
value_c = opts.value_c or { 235, 235, 235 },
sel_c   = opts.sel_c or { 249, 150, 0 },
deep_c  = opts.deep_c or { 100, 100, 110 },
stack = { { node = opts.root, cursor = 1, top = 1 } },
change = true,
sync = function(self) self.change = true end,
nav_cb = function(self, delta)
local f = self.stack[#self.stack]
local c = f.cursor + delta
if c < 1 then c = 1 end
local n = #f.node.items
if c > n then c = n end
if c ~= f.cursor then f.cursor = c; self:sync() end
end,
enter_cb = function(self)
local f = self.stack[#self.stack]
local it = f.node.items[f.cursor]
if not it then return end
if it.sub then
local node = (type(it.sub) == "function") and it.sub() or it.sub
self.stack[#self.stack + 1] = { node = node, cursor = 1, top = 1 }
self:sync()
elseif it.act then
it.act()
self:sync()
end
end,
back_cb = function(self)
if #self.stack > 1 then
self.stack[#self.stack] = nil
self:sync()
end
end,
resolve = function(self)
local node = self.root
for i = 2, #self.stack do
local pf = self.stack[i - 1]
local it = pf.node.items[pf.cursor]
if not it or not it.sub then break end
node = (type(it.sub) == "function") and it.sub() or it.sub
self.stack[i].node = node
end
for i = 1, #self.stack do
local f = self.stack[i]
local n = #f.node.items
if f.cursor > n then f.cursor = n end
if f.top > f.cursor then f.top = f.cursor end
end
end,
enc_cb = function(self, delta)
local f = self.stack[#self.stack]
local it = f.node.items[f.cursor]
if it and it.edit then
it.edit(delta)
self:resolve()
self:sync()
end
end,
render = function(self)
local lcd, x, y = self.lcd, self.x, self.y
local f = self.stack[#self.stack]
local node = f.node
lcd:draw_area_filled(x, y, x + self.w, y + self.h, self.bg)
lcd:draw_text_fast(node.title, x + self.pad, y + 8, 16, self.title_c)
if #self.stack > 1 then
lcd:draw_text_fast("<", x + self.w - self.pad - 16, y + 8, 16, self.label_c)
end
lcd:draw_line(x, y + 32, x + self.w, y + 32, self.rule)
local n = #node.items
if f.cursor < f.top then f.top = f.cursor end
if f.cursor > f.top + self.rows - 1 then f.top = f.cursor - self.rows + 1 end
local ty0 = y + 40
local rh = (self.h - 44) / self.rows
for r = 1, self.rows do
local i = f.top + r - 1
if i > n then break end
local it = node.items[i]
local iy = math.floor(ty0 + (r - 1) * rh)
local sel = (i == f.cursor)
if sel then
core.drawIndicator(lcd, x, iy, self.w, math.floor(rh),
{ kind = "bar-left", color = self.sel_c, thick = 3 })
end
local ty = math.floor(iy + (rh - 8) / 2)
lcd:draw_text_fast(it.label, x + self.pad + 6, ty, 8,
sel and self.sel_c or self.label_c)
local v
if it.sub then v = ">"
elseif it.value then v = it.value()
elseif it.act then v = "RUN"
else v = "" end
if v ~= "" then
lcd:draw_text_fast(v, x + self.w - self.pad - #v * 8, ty, 8,
it.sub and self.deep_c or (sel and self.sel_c or self.value_c))
end
end
end,
}
end
function M.label(opts)
opts = opts or {}
return {
text  = opts.text or "",
color = opts.color or { 110, 110, 120 },
size  = opts.size or 8,
set   = function(self, text) self.text = text; self.change = true end,
render = function(self)
local lcd = self.lcd
lcd:draw_area_filled(self.x, self.y, self.x + self.w, self.y + self.h, { 0, 0, 0 })
local tx = self.x + ((self.w - #self.text * self.size) // 2)
local ty = self.y + (self.h - self.size) // 2
lcd:draw_text_fast(self.text, tx, ty, self.size, self.color)
end,
}
end
return M
end)()

seq3 = { lanes = {} }
do
local gen_defaults = { kind = "gamut", hits = 4, spread = 12, downUp = 64,
velSpread = 30, gateSpread = 20, seed = 1 }
for lane = 1, 4 do
local t = {
type = "note", dims = "16x1", length = 16, division = 1, channel = lane,
scaleMask = 0xAB5, root = 0,
advanceSource = "transport.sixteenth",
xAdvanceSource = "transport.quarter",
yAdvanceSource = "transport.sixteenth",
controller = 20, midiNote = 36,
gen = {}, genTick = 0,
}
for k, v in pairs(gen_defaults) do t.gen[k] = v end
seq3.lanes[lane] = t
end
end
function seq3.get(lane, field) return seq3.lanes[lane][field] end
function seq3.set(lane, field, v) seq3.lanes[lane][field] = v end
function seq3.setType(lane, kind) seq3.set(lane, "type", kind) end
function seq3.setDimensions(lane, d) seq3.set(lane, "dims", d) end
function seq3.setLength(lane, n) seq3.set(lane, "length", n) end
function seq3.setDivision(lane, n) seq3.set(lane, "division", n) end
function seq3.setChannel(lane, ch) seq3.set(lane, "channel", ch) end
function seq3.setScale(lane, mask, root)
seq3.set(lane, "scaleMask", mask)
seq3.set(lane, "root", root)
end
function seq3.setAdvanceSource(lane, s) seq3.set(lane, "advanceSource", s) end
function seq3.setXAdvanceSource(lane, s) seq3.set(lane, "xAdvanceSource", s) end
function seq3.setYAdvanceSource(lane, s) seq3.set(lane, "yAdvanceSource", s) end
function seq3.generate(lane, opts)
local g = seq3.lanes[lane].gen
for k, v in pairs(opts) do g[k] = v end
seq3.lanes[lane].genTick = seq3.lanes[lane].genTick + 1
end
local TYPES = { "note", "mod", "trig", "gate" }
local DIMS  = { "16x1", "8x2", "5x3", "4x3", "4x4" }
local SOURCES = { "off", "transport.whole", "transport.half", "transport.quarter",
"transport.eighth", "transport.sixteenth" }
for i = 0, 7 do SOURCES[#SOURCES + 1] = "external." .. i end
for i = 1, 4 do SOURCES[#SOURCES + 1] = "lane." .. i end
local SCALES = {
{ name = "off",      mask = 0x000 },
{ name = "major",    mask = 0xAB5 },
{ name = "minor",    mask = 0x5AD },
{ name = "harm min", mask = 0x9AD },
{ name = "dorian",   mask = 0x6AD },
{ name = "phrygian", mask = 0x5AB },
{ name = "mixolyd",  mask = 0x6B5 },
{ name = "min pent", mask = 0x4A9 },
}
local NOTE_NAMES = { "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B" }
local function cycleItem(label, list, getf, setf)
return {
label = label,
value = function() return tostring(getf()) end,
edit = function(delta)
local cur = getf()
local idx = 1
for i = 1, #list do
if list[i] == cur then idx = i break end
end
idx = idx + delta
if idx < 1 then idx = 1 elseif idx > #list then idx = #list end
setf(list[idx])
end,
}
end
local function rangeItem(label, lo, hi, step, getf, setf, fmt)
return {
label = label,
value = function()
local v = getf()
return fmt and fmt(v) or tostring(v)
end,
edit = function(delta)
local v = getf() + delta * step
if v < lo then v = lo elseif v > hi then v = hi end
setf(v)
end,
}
end
local function scaleItem(lane)
local L = seq3.lanes[lane]
return {
label = "SCALE",
value = function()
local mask = L.scaleMask
for _, s in ipairs(SCALES) do
if s.mask == mask then return s.name end
end
return "0x" .. string.format("%03X", mask)
end,
edit = function(delta)
local idx = 1
for i, s in ipairs(SCALES) do
if s.mask == L.scaleMask then idx = i break end
end
idx = idx + delta
if idx < 1 then idx = 1 elseif idx > #SCALES then idx = #SCALES end
seq3.setScale(lane, SCALES[idx].mask, L.root)
end,
}
end
local function genNode(lane)
local G = seq3.lanes[lane].gen
local items = {
cycleItem("KIND", { "gamut", "euclid" },
function() return G.kind end, function(v) G.kind = v end),
}
if G.kind == "euclid" then
items[#items + 1] = rangeItem("HITS", 1, 16, 1,
function() return G.hits end, function(v) G.hits = v end)
else
items[#items + 1] = rangeItem("SPREAD", 0, 48, 1,
function() return G.spread end, function(v) G.spread = v end)
items[#items + 1] = rangeItem("D/U", 0, 127, 8,
function() return G.downUp end, function(v) G.downUp = v end,
function(v) return (v <= 42 and "below") or (v >= 85 and "above") or "mixed" end)
items[#items + 1] = rangeItem("VEL", 0, 127, 4,
function() return G.velSpread end, function(v) G.velSpread = v end)
items[#items + 1] = rangeItem("GATE", 0, 127, 4,
function() return G.gateSpread end, function(v) G.gateSpread = v end)
end
items[#items + 1] = rangeItem("SEED", 0, 9999, 1,
function() return G.seed end, function(v) G.seed = v end)
items[#items + 1] = {
label = "GEN NOW",
value = function()
local tick = seq3.lanes[lane].genTick
return tick > 0 and ("RUN x" .. tick) or "RUN"
end,
act = function()
seq3.generate(lane, {
kind = G.kind, hits = G.hits, spread = G.spread, downUp = G.downUp,
velSpread = G.velSpread, gateSpread = G.gateSpread, seed = G.seed,
})
end,
}
return { title = "GEN L" .. lane, items = items }
end
local function laneNode(lane)
local L = seq3.lanes[lane]
local items = {
cycleItem("TYPE", TYPES,
function() return L.type end, function(v) seq3.setType(lane, v) end),
cycleItem("DIMS", DIMS,
function() return L.dims end, function(v) seq3.setDimensions(lane, v) end),
}
if L.dims == "16x1" then
items[#items + 1] = rangeItem("LEN", 1, 16, 1,
function() return L.length end, function(v) seq3.setLength(lane, v) end)
items[#items + 1] = cycleItem("ADV", SOURCES,
function() return L.advanceSource end,
function(v) seq3.setAdvanceSource(lane, v) end)
else
items[#items + 1] = cycleItem("XADV", SOURCES,
function() return L.xAdvanceSource end,
function(v) seq3.setXAdvanceSource(lane, v) end)
items[#items + 1] = cycleItem("YADV", SOURCES,
function() return L.yAdvanceSource end,
function(v) seq3.setYAdvanceSource(lane, v) end)
end
items[#items + 1] = rangeItem("DIV", 1, 16, 1,
function() return L.division end, function(v) seq3.setDivision(lane, v) end)
items[#items + 1] = rangeItem("CHAN", 1, 16, 1,
function() return L.channel end, function(v) seq3.setChannel(lane, v) end)
if L.type == "note" then
items[#items + 1] = scaleItem(lane)
items[#items + 1] = rangeItem("ROOT", 0, 11, 1,
function() return L.root end, function(v) seq3.setScale(lane, L.scaleMask, v) end,
function(v) return NOTE_NAMES[v + 1] end)
end
items[#items + 1] = { label = "GEN", sub = function() return genNode(lane) end }
return { title = "LANE " .. lane, items = items }
end
local function rootNode()
local items = {}
for lane = 1, 4 do
items[lane] = { label = "LANE " .. lane, sub = function() return laneNode(lane) end }
end
return { title = "SEQ3 SETUP", items = items }
end
lcd = setmetatable({}, {
__index = function(_, name)
return function(_, ...) return _G[name](0, ...) end
end,
})
canvas = core.Layout:new()
canvas:initialize(lcd, nil, nil, 0, 0, 320, 240)
canvas:place(0, 0, 320, 220, MW.menu{ root = rootNode(), rows = 6 })
canvas:place(0, 220, 320, 20,
MW.label{ text = "KS0/1 MOVE KS2 OPEN KS3 BACK ENC EDIT" })
handleControl = function(index, delta)
if index == 8 then
canvas:dispatch("enc_cb", delta or 0)
elseif index >= 0 and index <= 7 then
if index == 0 then canvas:dispatch("nav_cb", -1)
elseif index == 1 then canvas:dispatch("nav_cb", 1)
elseif index == 2 then canvas:dispatch("enter_cb")
elseif index == 3 then canvas:dispatch("back_cb") end
else
if index == 9 then canvas:dispatch("enter_cb")
elseif index == 10 then canvas:dispatch("back_cb")
elseif index == 11 then canvas:dispatch("nav_cb", -1)
elseif index == 12 then canvas:dispatch("nav_cb", 1) end
end
end
end
-- INIT END

-- LOOP START
FRAME = (FRAME or 0) + 1
local sig = tostring(RC or 0)
if sig ~= EVSIG then
  EVSIG = sig
  local i = grid.event_index
  if i == 8 then
    if grid.encoder_delta ~= 0 and handleControl then handleControl(8, grid.encoder_delta) end
  elseif i >= 0 and grid.button_state[i] == 1 and handleControl then
    handleControl(i)
  end
end
if canvas then canvas:render(FRAME) end
-- LOOP END
