-- persist.lua — save/load engine state as Lua chunks. The only Core module
-- that does IO, and never on the pulse path.
--
-- Format: a Lua chunk returning { version=1, lanes={ ... } } — the same shape
-- as the hand-written presets/ files, so a saved slot stays readable and
-- hand-editable. Trigger/value sources are written as their public names
-- (docs/NAMING.md), not enums.
--
-- Load applies through Engine.loadPreset, preserving runtime lane identities.
-- Save is lossless against load: every field loadPreset reads, save writes.
-- Round-trip is covered by tests/run.lua.
--
-- DEVICE RULES (this module ships in dist/seq3x.lua): no string.format, no
-- table.concat, no math.type, no collectgarbage. Values go straight into
-- file:write, which accepts numbers — the same shape as seq-1's proven
-- on-device persist. Writing incrementally also means no whole-file string
-- is ever held in RAM.

local Engine  = require("engine")
local Sources = require("sources")
local Lane    = require("lane")

local M = {}

M.SLOTS = 24

-- Slot filename prefix. The Mac harness keeps slots in presets/; the Grid
-- module's file storage is FLAT (no directories — seq-1 ships "d0.lua"), so
-- the device adapter sets M.prefix = "s" and slots become "s01.lua".
M.prefix = "presets/"

function M.slotPath(slot)
    if type(slot) ~= "number" then return M.prefix .. tostring(slot) end
    local n = (slot < 10) and ("0" .. slot) or tostring(slot)
    return M.prefix .. n .. ".lua"
end

-- Step-array defaults, from Lane.new. An array is written only when it carries
-- the lane's own data or deviates from these, so files stay small.
local DEFAULT = { pitch = 60, velocity = 100, stepLength = 6, value = 0, gate = 0 }

-- Which arrays a lane type actually plays. Others are written only if dirty,
-- so switching a lane's type doesn't silently drop the data behind it.
local OWNED = {
    note = { pitch = true, velocity = true, stepLength = true },
    mod  = { value = true },
    trig = { gate = true },
    gate = { gate = true },
}

local ARRAY_ORDER = { "pitch", "velocity", "stepLength", "value", "gate" }

local SOURCE_FIELDS = {
    "advanceSource", "xAdvanceSource", "yAdvanceSource",
    "resetSource", "randomSource", "previousSource", "shiftSource",
    "addressSource", "xAddressSource", "yAddressSource",
}

local function isDirty(arr, default)
    for i = 1, Lane.CAP do
        if arr[i] ~= default then return true end
    end
    return false
end

local function writeArray(out, name, arr)
    out:write("            ", name, " = {")
    for i = 1, Lane.CAP do
        if i > 1 then out:write(", ") end
        out:write(arr[i])
    end
    out:write("},\n")
end

-- Write the live engine state as a Lua chunk into `out` (anything with a
-- :write method — a file handle on the device, a buffer on the Mac).
local function dump(out)
    out:write("-- seq3 saved state. Generated by src/core/persist.lua.\n")
    out:write("return {\n    version = 1,\n    lanes = {\n")

    for i = 1, #Engine.lanes do
        local l = Engine.lanes[i]
        out:write("        {\n")
        out:write("            type = \"", l.type, "\", channel = ", l.channel,
                  ", dims = \"", l.dims, "\", length = ", l.length,
                  ", division = ", l.division, ",\n")
        out:write("            controller = ", l.controller,
                  ", midiNote = ", l.midiNote,
                  ", scaleMask = ", l.rawScaleMask,
                  ", root = ", l.root, ",\n")
        out:write("            minNote = ", l.minNote, ", maxNote = ", l.maxNote,
                  ", minValue = ", l.minValue, ", maxValue = ", l.maxValue, ",\n")

        -- Sources: names, and only the ones that are actually routed.
        for k = 1, #SOURCE_FIELDS do
            local f = SOURCE_FIELDS[k]
            if l[f] ~= Sources.OFF then
                out:write("            ", f, " = \"", Sources.name(l[f]), "\",\n")
            end
        end
        if l.shiftSource ~= Sources.OFF or l.shiftAmount ~= 1 then
            out:write("            shiftAmount = ", l.shiftAmount, ",\n")
        end

        local owned = OWNED[l.type] or OWNED.note
        for k = 1, #ARRAY_ORDER do
            local name = ARRAY_ORDER[k]
            if owned[name] or isDirty(l[name], DEFAULT[name]) then
                writeArray(out, name, l[name])
            end
        end

        -- A live generator is restored with fill = false: the steps written
        -- above are authoritative, and `seed` carries the RNG state so a live
        -- lane continues its sequence rather than restarting it.
        if l.generator == 1 then
            out:write("            generate = { kind = \"gamut\", base = ", l.genBase,
                      ", spread = ", l.genSpread, ", downUp = ", l.genDownUp, ",\n",
                      "                         velSpread = ", l.genVelSpread,
                      ", gateSpread = ", l.genGateSpread,
                      ", seed = ", l.rng, ",\n",
                      "                         live = true, fill = false },\n")
        end

        out:write("        },\n")
    end

    out:write("    },\n}\n")
end

function M.save(path)
    local f, err = io.open(path, "w")
    if not f then return false, err end
    dump(f)
    f:close()
    return true
end

function M.load(path)
    local f, err = io.open(path, "r")
    if not f then return false, err end
    local src = f:read("*a")
    f:close()
    local chunk, cerr = load(src, "preset", "t")
    if not chunk then return false, cerr end
    local ok, data = pcall(chunk)
    if not ok then return false, data end
    return Engine.loadPreset(data)
end

function M.saveSlot(slot) return M.save(M.slotPath(slot)) end
function M.loadSlot(slot) return M.load(M.slotPath(slot)) end

-- Host-side convenience: the same chunk as a string. Not reachable from the
-- device paths above (this is the only place table.concat appears).
function M.serialize()
    local buf = { n = 0 }
    function buf:write(...)
        local n = self.n
        for i = 1, select("#", ...) do
            n = n + 1
            self[n] = tostring((select(i, ...)))
        end
        self.n = n
    end
    dump(buf)
    return table.concat(buf, "", 1, buf.n)
end

return M
