-- seq3 saved state. Generated by src/core/persist.lua.
return {
    version = 1,
    lanes = {
        {
            type = "note", channel = 1, dims = "4x4", length = 16, division = 1,
            controller = 1, midiNote = 60, scaleMask = 1453, root = 9,
            minNote = 0, maxNote = 127, minValue = 0, maxValue = 127,
            xAdvanceSource = "transport.sixteenth",
            yAdvanceSource = "transport.quarter",
            pitch = {69, 72, 76, 81, 67, 70, 74, 79, 65, 68, 72, 77, 63, 66, 70, 75},
            velocity = {80, 90, 100, 110, 80, 90, 100, 110, 80, 90, 100, 110, 80, 90, 100, 110},
            stepLength = {3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3},
        },
        {
            type = "mod", channel = 2, dims = "16x1", length = 16, division = 1,
            controller = 74, midiNote = 60, scaleMask = 2741, root = 0,
            minNote = 0, maxNote = 127, minValue = 10, maxValue = 120,
            advanceSource = "transport.eighth",
            value = {15, 30, 45, 60, 75, 90, 105, 120, 120, 105, 90, 75, 60, 45, 30, 15},
        },
        {
            type = "trig", channel = 10, dims = "16x1", length = 16, division = 1,
            controller = 1, midiNote = 36, scaleMask = 2741, root = 0,
            minNote = 0, maxNote = 127, minValue = 0, maxValue = 127,
            advanceSource = "transport.sixteenth",
            gate = {1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0},
        },
        {
            type = "gate", channel = 4, dims = "16x1", length = 8, division = 1,
            controller = 1, midiNote = 40, scaleMask = 2741, root = 0,
            minNote = 0, maxNote = 127, minValue = 0, maxValue = 127,
            advanceSource = "transport.quarter",
            gate = {1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0},
        },
    },
}
